export { default as HomePage } from './Home';
export { default as AboutPage } from './About';
export { default as NotFoundPage } from './NotFound';
export { default as PostPage } from './Post';
export { default as UserProfilePage } from './UserProfile';
export { default as EditProfilePage } from './EditProfile';
export { default as SignUp } from './SignUp';
export { default as Login } from './Login';
export { default as Controversy } from './Controversy';
